# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'capybara'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'faker'
gem 'httparty'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'site_prism'
