apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    circleci.com/project-slug: github/Creditas/oi
    creditas.io/expose-type: internal
  description: Test Application
  labels:
    creditas.io/language: Python
    creditas.io/tribe: tribe-bsp
  name: challenge
spec:
  lifecycle: experimental
  owner: tribe-bsp
  type: service
