require './bootstrap'

task default: %w[original_book_example]

desc "Original book example extracted from initial bootstrap.rb version"
task :original_book_example do
  # Book Example (build new payments if you need to properly test it)

  address = Address.new(zipcode: '12345-678')
  foolano = Customer.new(
    name: "Jimmy",
    email: "jimmy@jimmy.org",
    address: address
  )
  book = Product::PhysicalBook.new(name: 'Awesome book', price: 15)
  book_order = Order.new(foolano)
  book_order.add_product(book)

  payment_book = Payment.new(
    order: book_order,
    payment_method: CreditCard.fetch_by_hashed('43567890-987654367')
  )
  payment_book.pay

  p payment_book.paid? # < true
  p payment_book.order.items.first.product.type
end
