name: Catalog-info.yaml validation

on:
  workflow_call:
permissions:
  id-token: write
  contents: write
jobs:
  validate-catalog-info:
    name: Catalog-info.yaml validation
    runs-on: ubuntu-latest
    steps:
      - uses: creditas/developerhub/actions/validator@master